filter:
  excluded_paths:
  - tests/*
  - tmp/*

checks:
  php:
    no_global_keyword: false
    psr2_switch_declaration: false
    psr2_control_structure_declaration: false
    psr2_class_declaration: false
    avoid_superglobals: false

tools:
  sensiolabs_security_checker: true
  external_code_coverage: true